version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_THIRDWEB_CLIENT_ID: ${NEXT_PUBLIC_THIRDWEB_CLIENT_ID}
        PINATA_KEY: ${PINATA_KEY}
        PINATA_SECRET: ${PINATA_SECRET}
    ports:
      - '3000:3000'
    env_file:
      - .env
